def transform_json_data_into_department_model(
    department_model, department_json):
    department_model.CompanyID=department_json['CompanyID']
    department_model.DepartmentTypeID=department_json['DepartmentTypeID']
    department_model.ActiveFlag=department_json['ActiveFlag']
    department_model.DepartmentDescription=department_json['DepartmentDescription']
    department_model.DisplayPromptMethodID=department_json['DisplayPromptMethodID']
    department_model.AudibleAgeVerificationAlertFlag=department_json['AudibleAgeVerificationAlertFlag']
    department_model.IsModified=department_json['IsModified']
    department_model.IsDepartmentOpen=department_json['IsDepartmentOpen']
    department_model.IsFractionalQtyAllowedFlag=department_json['IsFractionalQtyAllowedFlag']
    department_model.IsLoyaltyRedeemEligibleFlag=department_json['IsLoyaltyRedeemEligibleFlag']
    department_model.PriceRequiredFlag=department_json['PriceRequiredFlag']
    department_model.IsItemReturnableFlag=department_json['IsItemReturnableFlag']
    department_model.AreSpecialDiscountsAllowedFlag=department_json['AreSpecialDiscountsAllowedFlag']
    department_model.DepartmentProfitMargin=department_json['DepartmentProfitMargin']
    department_model.AllowFoodStampsFlag=department_json['AllowFoodStampsFlag']
    department_model.MinimumOpenSaleAmount=department_json['MinimumOpenSaleAmount']
    department_model.MaximumOpenSaleAmount=department_json['MaximumOpenSaleAmount']
    department_model.CreatedDateTime=department_json['CreatedDateTime']
    department_model.LastModifiedBy=department_json['LastModifiedBy']
    department_model.LastModifiedDateTime=department_json['LastModifiedDateTime']
    department_model.ProfitPercent=department_json['ProfitPercent']
    department_model.ChartofAccounttypeid=department_json['ChartofAccounttypeid']
    department_model.ChartOfAccountTypeName=department_json['ChartOfAccountTypeName']
    return department_model